# Autogenerated wrapper script for PlaSim_jll for x86_64-linux-gnu-libgfortran3
export plasim_t21_l10_p1, plasim_t21_l20_p1, plasim_t42_l10_p1, plasim_t42_l20_p1

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("PlaSim")
JLLWrappers.@declare_executable_product(plasim_t21_l10_p1)
JLLWrappers.@declare_executable_product(plasim_t21_l20_p1)
JLLWrappers.@declare_executable_product(plasim_t42_l10_p1)
JLLWrappers.@declare_executable_product(plasim_t42_l20_p1)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        plasim_t21_l10_p1,
        "bin/plasim_t21_l10_p1",
    )

    JLLWrappers.@init_executable_product(
        plasim_t21_l20_p1,
        "bin/plasim_t21_l20_p1",
    )

    JLLWrappers.@init_executable_product(
        plasim_t42_l10_p1,
        "bin/plasim_t42_l10_p1",
    )

    JLLWrappers.@init_executable_product(
        plasim_t42_l20_p1,
        "bin/plasim_t42_l20_p1",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
